
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Mar 16 17:28:26 GMT 2013
//----------------------------------------------------

package Q;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int POWER = 9;
  public static final int CHAR = 43;
  public static final int CONCAT = 11;
  public static final int GREATER = 15;
  public static final int SEMI = 27;
  public static final int REPEAT = 39;
  public static final int INT = 45;
  public static final int LESS = 13;
  public static final int MINUS = 6;
  public static final int NOT = 2;
  public static final int LCURL = 19;
  public static final int AND = 4;
  public static final int TYPE = 48;
  public static final int LTUPLE = 30;
  public static final int IN = 10;
  public static final int OR = 3;
  public static final int TDEF = 33;
  public static final int BOOL = 47;
  public static final int COMMA = 28;
  public static final int UNTIL = 38;
  public static final int PLUS = 5;
  public static final int ASSIGN = 25;
  public static final int IF = 34;
  public static final int RTUPLE = 31;
  public static final int ID = 41;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int LPRAN = 21;
  public static final int error = 1;
  public static final int NEQ = 18;
  public static final int FDEF = 32;
  public static final int VOID = 42;
  public static final int EQ = 17;
  public static final int RCURL = 20;
  public static final int EQLESS = 14;
  public static final int TIMES = 7;
  public static final int COLON = 26;
  public static final int ELSE = 35;
  public static final int LBRACE = 23;
  public static final int WHILE = 37;
  public static final int FLOAT = 46;
  public static final int RBRACE = 24;
  public static final int STRING = 44;
  public static final int LEN = 12;
  public static final int GREATEREQ = 16;
  public static final int RPRAN = 22;
  public static final int DO = 36;
}

